apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-app
  namespace: http-request-hpa
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - http-request-hpa

  selector:
    matchLabels:
      app: nodejs-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s